spring:
  datasource:
    url: jdbc:mysql://139.224.48.178:3306/qmall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数

logging:
  level:
    root: info
    com.zhian.mall: debug
